### PR TITLE
node express and postgresql (fixes #9)

### LINKED ISSUE #9: Create node express backend to connect with postgresql

### PR DESCRIPTION
**Pull request by robinGiri**
Fixes: #9 
Set up
1. Express
2. PostgreSQL
3. Sequelize ORM

### CODE REVIEW

**Review by lmmrssa — COMMENTED** [review]
Also add table creation (migration) scripts

**Comment by robinGiri** [comment]
> Also add table creation (migration) scripts

Thanks for your review I'm on it next.

**Comment by lmmrssa** [comment]
Just for reference
```
lmmrssa@Laxmans-MacBook-Pro api % npm start

> planetformsbackend@1.0.0 start
> nodemon server

[nodemon] 2.0.7
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node server.js`
PlanetFarms is running on PORT 5000.
Error: SequelizeConnectionError: role "postgres" does not exist
[nodemon] restarting due to changes...
[nodemon] starting `node server.js`
PlanetFarms is running on PORT 5000.
Error: SequelizeHostNotFoundError: getaddrinfo ENOTFOUND db
[nodemon] restarting due to changes...
[nodemon] restarting due to changes...
[nodemon] starting `node server.js`
[nodemon] restarting due to changes...
[nodemon] starting `node server.js`
PlanetFarms is running on PORT 5000.
Error: SequelizeConnectionError: role "test" does not exist
[nodemon] restarting due to changes...
[nodemon] restarting due to changes...
[nodemon] starting `node server.js`
PlanetFarms is running on PORT 5000.
Error: SequelizeConnectionError: connect ETIMEDOUT 172.23.0.2:5432
[nodemon] restarting due to changes...
[nodemon] starting `node server.js`
[nodemon] restarting due to changes...
[nodemon] starting `node server.js`
PlanetFarms is running on PORT 5000.
Error: SequelizeConnectionError: role "test" does not exist
```

**Comment by robinGiri** [comment]
@lmmrssa  I'm done with creating Users table with migration Can you review it once? Thanks.

**Review by lmmrssa — APPROVED** [review]

**Review by lmmrssa — APPROVED** [review]

**Review by dogi — APPROVED** [review]

**Pull request merged**
