### PR TITLE
mycourses overview and detail (fixes #196)

### LINKED ISSUE #196: My courses and collection page (Courses screen)

### PR DESCRIPTION
**Pull request by SujalLama**

### CODE REVIEW

**Review by lmmrssa — CHANGES_REQUESTED** [review]
my courses page has spacing on left and elements does not cover space.

**Review by lmmrssa — CHANGES_REQUESTED** [review]
At this big screen it should have move items on the screen not just two
image

**Comment by SujalLama** [comment]
> At this big screen it should have move items on the screen not just two
> image

I have created three columns above 1500px width and 2 columns in mid range and 1 column for mobile.

**Comment by lmmrssa** [comment]
Height seems to be too small so button covers title
image

**Review by lmmrssa — CHANGES_REQUESTED** [review]
Width of time is changing based on number of item available instead it should be based on how many number each screen size will contain.
My collection and collection should have same size irrespective of the number of records available
image

**Review by lmmrssa — APPROVED** [review]

**Review by dogi — APPROVED** [review]

**Pull request merged**
