### PR TITLE
Use email as username

### PR DESCRIPTION
**Pull request by neil-sweetcodepro**
1. Use email as user's username 
2. Change req.body.name to use req.body.username for consistency across endpoints.

### CODE REVIEW

**Comment by neil-sweetcodepro** [comment]
To be reviewed and merged after https://github.com/earthowned/planetfarms/pull/514

**Comment by lmmrssa** [comment]
Along with issues mentioned on other PR.
4. When testing for forgot password it does not seem to work. Give code warning
5. When trying to register new user, only email is allowed but there is no screen for verifying email address. So it gives invalid token error

**Comment by neil-sweetcodepro** [comment]
@lmmrssa we'll be forced to use emails for new users in registration. You won't be able to log in and confirm the code using the frontend. There will be frontend changes to follow after this PR.

**Comment by neil-sweetcodepro** [comment]
@lmmrssa fixed issue 4. In order to confirm/verify email address, send request directly to the backend.
Make a request to `/api/users/confirm-sign-up` endpoint with the sample json payload:
```
{
    "username": "test@test.com",
    "code": "666704"
}
```

To resend the sign up code, make a request to `POST /api/users/resend-sign-up-code` with the sample json payload:
```
{
  "username": "test@test.com"
}
```

**Review by lmmrssa — APPROVED** [review]

**Pull request merged**
