### PR TITLE
fix sidebar and dashboard layout

### PR DESCRIPTION
**Pull request by ZheleznovTN**
1. Update Side Menu as in designs (fix animations);
2. Update Bottom Nav for mobile;
3. Update Header (desktop/mobile);
4. Implement Modal Button Component;
5. Implement Messages Modal (desktop/mobile) / fix app crash;
6. Implement Notifications Modal (desktop/mobile) / fix app crash;
7. Implement Settings Modal (only desktop, will request designs for mobile from designer);
8. Update Not Found Page;
9. Use Portal for showing modals;
10. Fix and cleanup Dashboard Layout (container for all pages);
11. Implement Logout Modal (desktop/mobile);
12. Implement Change Password Modal (desktop/mobile);
13. Implement Mobile Navigation Menu;
14. Move Routes from App.jsx to routes directory;
15. Clean Up;

### CODE REVIEW

**Comment by ZheleznovTN** [comment]
@dogi @lmmrssa big sorry for big pull request, but one fix raise one more bug or problem. so had not possibility to chunk this stuff.

**Comment by dogi** [comment]
image
top navigation looks awesome but sidenavi is strange

image
people and menu button strange

**Comment by lmmrssa** [comment]
@dogi ui seems to be working for me.

**Comment by dogi** [comment]
> @dogi ui seems to be working for me.

@lmmrssa when I push the branch to http://github.planetfarms.io:3000 it breaks too

image

which means it is a linux thing ... filenames maybe

**Comment by lmmrssa** [comment]
by looking into github.planetfarms.io:3000 found https://github.com/earthowned/planetfarms/blob/dd3c0e3ff3acd80cd7d03b0cd54034ff4ac8adae/src/common/links/side-nav-link/index.jsx#L32 is causing issue due to function being called and it seems to be issue only seen in linux system. looking into more such issues will raise it as we find it.

**Review by lmmrssa — APPROVED** [review]

**Review by dogi — APPROVED** [review]

**Pull request merged**
