### PR TITLE
implement article page

### PR DESCRIPTION
**Pull request by ZheleznovTN**
implement article page

### CODE REVIEW

**Review by dogi — COMMENTED** [review]
image

think I found 2 buhbuhs
- `unknown user` should say in my case `dogi treehouses` ... also no avatar
- on Video the "Video Title" is there but "Description" got lost

**Comment by ZheleznovTN** [comment]
> image
> 
> think I found 2 buhbuhs
> 
> * `unknown user` should say in my case `dogi treehouses` ... also no avatar
> * on Video the "Video Title" is there but "Description" got lost

**Comment by ZheleznovTN** [comment]
1. Unknown user - because "user info" api isn't working.
2. I will fix it in next pr

**Comment by lmmrssa** [comment]
#508

**Pull request closed without merging**
