### PR TITLE
course members page

### PR DESCRIPTION
**Pull request by ZheleznovTN**
1. Members Page;
2. With fake data for now;

### CODE REVIEW

**Comment by ZheleznovTN** [comment]
@dogi @lmmrssa fixed conflicts

**Comment by lmmrssa** [comment]
image

Empty space on top left next to course detail does not look that good as content of course gets longer. May be letting designer know about it and adjust design accordingly.

**Comment by ZheleznovTN** [comment]
> image
> 
> Empty space on top left next to course detail does not look that good as content of course gets longer. May be letting designer know about it and adjust design accordingly.

you mean height of header? yeah, you are right, i think we can make it like a youtube style. I mean transparent header, and scroll all content under a header. i already create a task for it.

**Comment by lmmrssa** [comment]
Screen Shot 2022-05-16 at 22 01 20
I mean space next to course description before members list. It does not look that bad if course description is short but when its too long empty space looks odd

**Comment by ZheleznovTN** [comment]
@lmmrssa content blocks don't need to be so long, it's design rule to make reading for user easier

**Review by dogi — APPROVED** [review]

**Review by lmmrssa — APPROVED** [review]

**Pull request merged**
