### PR TITLE
article preview

### PR DESCRIPTION
**Pull request by ZheleznovTN**
Implemented Article Preview before submitting

### CODE REVIEW

**Review by dogi — APPROVED** [review]
image

- unknown user again
- also going back from preview to edit lost the community selection

**Comment by dogi** [comment]
think once we solve merge conflict one or maybe both buhbuhs are gone

**Comment by ZheleznovTN** [comment]
@dogi conflicts fixed

**Comment by dogi** [comment]
> think once we solve merge conflict one or maybe both buhbuhs are gone cause edit fixes are missing

to bad still they are still here

**Review by lmmrssa — APPROVED** [review]

**Pull request merged**
