### PR TITLE
saved-collection: courses-screen (fixes: #200 )

### PR DESCRIPTION
**Pull request by SujalLama**

### CODE REVIEW

**Review by lmmrssa — CHANGES_REQUESTED** [review]
Height seems to be too small so button covers title
image

**Review by lmmrssa — APPROVED** [review]

**Review by dogi — CHANGES_REQUESTED** [review]
@SujalLama none of the screen sizes was using the full potential (many empty black spots)

**Review by lmmrssa — CHANGES_REQUESTED** [review]
Please look on this UI spacing

**Comment by SujalLama** [comment]
> @SujalLama none of the screen sizes was using the full potential (many empty bl

**Pull request closed without merging**
