### PR TITLE
Courses API

### PR DESCRIPTION
**Pull request by neil-sweetcodepro**
Courses API changes:
- Upload images - POST /api/photos
- Create course - POST /api/courses
- Update a course - PUT /api/courses/:id
- Delete a course - DELETE /api/courses/:id
- Get courses - GET /api/courses
- Get course by id - GET /api/courses/:id

Need to be logged in in order to access the APIs (need bearer token).

In order to add a course description with an image, you need to upload the image first and then use the image URL from the response.

### CODE REVIEW

**Comment by lmmrssa** [comment]
Its somehow difficult to know which fields are required and which are not when looking into Postman. It takes some try to understand it. Also when certain fields are not passed it gives error from code such as
Screen Shot 2022-05-10 at 22 51 15
We should avoid code error and return error message that can be sent to user.
Also structure of text, photo seems like it can be multiple item but when sending it on api its not clear how to send multiple. So far was able to send one text and image

**Comment by neil-sweetcodepro** [comment]
@lmmrssa can be checked again. Kindly check the description since there were changes in the body structure of the APIs. Our postman collection is updated as well,

**Comment by lmmrssa** [comment]
Screen Shot 2022-05-16 at 13 51 51

**Comment by neil-sweetcodepro** [comment]
@lmmrssa is that from a clean migration? can you try db migration and db seed with a clean db?

**Comment by lmmrssa** [comment]
not sure if having pull path in media is right approach
```
{
    "title": "Sample title",
    "price": 12.12,
    "isPublished": true,
    "thumbnail": "http://localhost:5000/resources/1.jpg",
    "description": [
        { "image": "http://localhost:5000/resources/images/2.jpg", "description": "img description (order 1)" },
        { "text": "text description 1 (order 2)", "heading": "text heading" },
        { "image": "http://localhost:5000/resources/images/3.jpg", "description": "img description (order 3)" }
    ]
}
```
For example If we change domain name then this will not work. May be if we assume there to be cdn path which will be same irrespective of application url then it might be ok.
Also how will we send image attachment. will there be different request to upload them before creating course?

**Comment by dogi** [comment]
@neil-sweetcodepro usually CDN have their own URL which might vary based on CDN system/service we use and/or instance we create
-> in other words relative URLs make us more flexible

**Comment by neil-sweetcodepro** [comment]
@lmmrssa @dogi fixed this and updated the postman

**Review by dogi — APPROVED** [review]

**Pull request merged**
